# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaxFree' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.4'
  pod 'Firebase/Analytics'
  pod 'DKChainableAnimationKit', '~> 2.0.0'
  pod 'Toast-Swift', '~> 5.0.0'

end
